apiVersion: v1
kind: ConfigMap
metadata:
  name: cd-postgres-config
  namespace: checkdev
data:
  POSTGRES_DB: cd_auth

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cd-app-config
  namespace: checkdev
data:
  SECURITY_OAUTH2_RESOURCE_USERINFOURL: http://cd-auth-svc:9900/user
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://cd-eureka-svc:9009/eureka
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SPRING_CLOUD_DISCOVERY_RETRY_MAX_ATTEMPTS: "10"
  BOT_USERNAME: checkdev_bot
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cd-postgres-init
  namespace: checkdev
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    for db in cd_auth cd_desc cd_mock cd_notification cd_generator; do
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        SELECT 'CREATE DATABASE $db' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$db')\gexec
    EOSQL
    done