apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cd-kafka-pvc
  namespace: checkdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-kafka-dpl
  namespace: checkdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd-kafka
  template:
    metadata:
      labels:
        app: cd-kafka
    spec:
      containers:
        - name: cd-kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9094
          readinessProbe:
            exec:
              command: [ "sh", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: [ "sh", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://cd-kafka-svc:9092,EXTERNAL://localhost:9094
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@localhost:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: cd-kafka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cd-kafka-svc
  namespace: checkdev
spec:
  type: ClusterIP
  selector:
    app: cd-kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092